### ISSUE TITLE
install/configure megaTinyCore 

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/tetra-workspace-image#1]
update `playbook.yaml` to install [megaTinyCore](https://github.com/SpenceKonde/megaTinyCore)

**Comment by mechatroniks-git** [comment]
To add the megatinycore, add this to the Additional Boards Manager URLs

`http://drazzy.com/package_drazzy.com_index.json`

![image](https://user-images.githubusercontent.com/57600622/220505805-fa05f438-6bc1-48bc-bada-184e51593899.png)
